---
apiVersion: v1
kind: Service
metadata:
  name: trivia
spec:
  selector:
    app: trivia
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trivia
  labels:
    app: trivia
spec:
  selector:
    matchLabels:
      app: trivia
  replicas: 1
  template:
    metadata:
      labels:
        app: trivia
    spec:
      containers:
      - name: trivia
        image: us.gcr.io/progmux-167421/trivia:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
        ports:
        - containerPort: 80
        volumeMounts:
          - name: env
            mountPath: /home/node/secrets
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=progmux-167421:us-west1:trivia=tcp:3306",
                  "-credential_file=/secrets/cloudsql/cloudsql-client-key.json"]
        volumeMounts:
          - name: cloudsql-client-key
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: env
          secret:
            secretName: env
        - name: cloudsql-client-key
          secret:
            secretName: cloudsql-client-key
